// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
	"time"
)

type Bookmark struct {
	ID        int64
	AuthorID  string
	ChannelID string
	Content   string
	CreatedAt time.Time
	DueAt     sql.NullTime
	GuildID   string
	MessageID string
	Timestamp time.Time
	UpdatedAt time.Time
	UserID    string
}
